name: CI
on:
  pull_request:
    branches:
      - humble
  push:
    branches:
      - humble

jobs:
  ros_ci:
    name: ros CI
    runs-on: ubuntu-latest
    container:
      image: rostooling/setup-ros-docker:ubuntu-jammy-latest
    steps:
      - name: Build and test
        uses: ros-tooling/action-ros-ci@v0.2
        with:
          target-ros2-distro: humble
          vcs-repo-file-url: https://raw.githubusercontent.com/meta-control/mc_mros_reasoner/humble/mros2_reasoner.rosinstall
